const featureConfig = {
  connections: {
    title: 'Connections',
    icon: '🔗',
    description: 'Manage data source and destination connections',
    endpoint: '/connections',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'host', label: 'Host' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['REST', 'SOAP', 'GraphQL', 'SFTP', 'Database'], required: true },
      { key: 'host', label: 'Host', type: 'text' },
      { key: 'port', label: 'Port', type: 'number' },
      { key: 'authType', label: 'Auth Type', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'error'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'inactive', 'error'],
  },
  apis: {
    title: 'APIs',
    icon: '🌐',
    description: 'Register and manage API integrations',
    endpoint: '/apis',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'method', label: 'Method' },
      { key: 'endpoint', label: 'Endpoint' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'method', label: 'Method', type: 'select', options: ['GET', 'POST', 'PUT', 'DELETE'], required: true },
      { key: 'endpoint', label: 'Endpoint', type: 'text', required: true },
      { key: 'version', label: 'Version', type: 'text' },
      { key: 'rateLimit', label: 'Rate Limit', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'deprecated', 'draft'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'deprecated', 'draft'],
  },
  workflows: {
    title: 'Workflows',
    icon: '⚡',
    description: 'Design and manage integration workflows',
    endpoint: '/workflows',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'triggerType', label: 'Trigger' },
      { key: 'status', label: 'Status', isStatus: true },
      { key: 'lastRun', label: 'Last Run', isDate: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'triggerType', label: 'Trigger Type', type: 'select', options: ['schedule', 'webhook', 'manual', 'event'], required: true },
      { key: 'stepsCount', label: 'Steps', type: 'number' },
      { key: 'successRate', label: 'Success Rate (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'paused', 'draft', 'error'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'paused', 'draft', 'error'],
  },
  transformations: {
    title: 'Transformations',
    icon: '🔄',
    description: 'Data transformation rules and mappings',
    endpoint: '/transformations',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'sourceFormat', label: 'Source' },
      { key: 'targetFormat', label: 'Target' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'sourceFormat', label: 'Source Format', type: 'select', options: ['JSON', 'XML', 'CSV', 'YAML'], required: true },
      { key: 'targetFormat', label: 'Target Format', type: 'select', options: ['JSON', 'XML', 'CSV', 'YAML'], required: true },
      { key: 'mappingCount', label: 'Mapping Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'inactive'],
  },
  connectors: {
    title: 'Connectors',
    icon: '🔌',
    description: 'Pre-built integration connectors',
    endpoint: '/connectors',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'provider', label: 'Provider' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'provider', label: 'Provider', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['CRM', 'ERP', 'Database', 'Cloud', 'Messaging', 'Analytics'], required: true },
      { key: 'version', label: 'Version', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['available', 'installed', 'deprecated'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['available', 'installed', 'deprecated'],
  },
  endpoints: {
    title: 'Endpoints',
    icon: '📡',
    description: 'API endpoints and service URLs',
    endpoint: '/endpoints',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'path', label: 'Path' },
      { key: 'method', label: 'Method' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'path', label: 'Path', type: 'text', required: true },
      { key: 'method', label: 'Method', type: 'select', options: ['GET', 'POST', 'PUT', 'DELETE'], required: true },
      { key: 'authRequired', label: 'Auth Required', type: 'select', options: ['true', 'false'] },
      { key: 'rateLimit', label: 'Rate Limit', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'inactive'],
  },
  schedules: {
    title: 'Schedules',
    icon: '⏰',
    description: 'Scheduled tasks and cron jobs',
    endpoint: '/schedules',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'cronExpression', label: 'Cron' },
      { key: 'status', label: 'Status', isStatus: true },
      { key: 'nextRun', label: 'Next Run', isDate: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'cronExpression', label: 'Cron Expression', type: 'text', required: true },
      { key: 'timezone', label: 'Timezone', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'paused', 'completed'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'paused', 'completed'],
  },
  logs: {
    title: 'Logs',
    icon: '📋',
    description: 'System and integration logs',
    endpoint: '/logs',
    columns: [
      { key: 'level', label: 'Level', isStatus: true },
      { key: 'action', label: 'Action' },
      { key: 'resourceType', label: 'Resource' },
      { key: 'details', label: 'Details' },
      { key: 'createdAt', label: 'Timestamp', isDate: true },
    ],
    fields: [
      { key: 'level', label: 'Level', type: 'select', options: ['info', 'warning', 'error', 'debug'], required: true },
      { key: 'action', label: 'Action', type: 'text', required: true },
      { key: 'resourceType', label: 'Resource Type', type: 'text' },
      { key: 'resourceId', label: 'Resource ID', type: 'number' },
      { key: 'details', label: 'Details', type: 'textarea' },
      { key: 'ipAddress', label: 'IP Address', type: 'text' },
    ],
    statuses: ['info', 'warning', 'error', 'debug'],
  },
  alerts: {
    title: 'Alerts',
    icon: '🔔',
    description: 'Notification and alert rules',
    endpoint: '/alerts',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'severity', label: 'Severity', isStatus: true },
      { key: 'channel', label: 'Channel' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'], required: true },
      { key: 'channel', label: 'Channel', type: 'select', options: ['email', 'slack', 'webhook', 'sms'], required: true },
      { key: 'condition', label: 'Condition', type: 'text' },
      { key: 'threshold', label: 'Threshold', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'muted', 'triggered'], required: true },
    ],
    statuses: ['active', 'muted', 'triggered'],
  },
  webhooks: {
    title: 'Webhooks',
    icon: '🪝',
    description: 'Incoming and outgoing webhooks',
    endpoint: '/webhooks',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'url', label: 'URL' },
      { key: 'events', label: 'Events' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'url', label: 'URL', type: 'text', required: true },
      { key: 'events', label: 'Events', type: 'text' },
      { key: 'secret', label: 'Secret', type: 'password' },
      { key: 'retryCount', label: 'Retry Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'inactive'],
  },
  templates: {
    title: 'Templates',
    icon: '📦',
    description: 'Reusable integration templates',
    endpoint: '/templates',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'complexity', label: 'Complexity' },
      { key: 'rating', label: 'Rating' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text', required: true },
      { key: 'complexity', label: 'Complexity', type: 'select', options: ['beginner', 'intermediate', 'advanced'], required: true },
      { key: 'estimatedTime', label: 'Estimated Time', type: 'text' },
      { key: 'stepsCount', label: 'Steps', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['beginner', 'intermediate', 'advanced'],
  },
  users: {
    title: 'Users',
    icon: '👥',
    description: 'User accounts and access control',
    endpoint: '/users',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'role', label: 'Role', type: 'select', options: ['admin', 'editor', 'viewer'], required: true },
      { key: 'password', label: 'Password', type: 'password' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'pending'], required: true },
    ],
    statuses: ['active', 'inactive', 'pending'],
  },
  settings: {
    title: 'Settings',
    icon: '⚙️',
    description: 'System configuration and preferences',
    endpoint: '/settings',
    columns: [
      { key: 'key', label: 'Key' },
      { key: 'value', label: 'Value' },
      { key: 'category', label: 'Category' },
    ],
    fields: [
      { key: 'key', label: 'Key', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['general', 'security', 'integration', 'notification', 'performance'] },
      { key: 'isSecret', label: 'Is Secret', type: 'select', options: ['true', 'false'] },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: [],
  },
  'error-retries': {
    title: 'Error Retries',
    icon: '🔁',
    description: 'Error handling and retry policies',
    endpoint: '/error-retries',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'maxRetries', label: 'Max Retries' },
      { key: 'backoffStrategy', label: 'Strategy' },
      { key: 'status', label: 'Status', isStatus: true },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'maxRetries', label: 'Max Retries', type: 'number', required: true },
      { key: 'backoffStrategy', label: 'Backoff Strategy', type: 'select', options: ['linear', 'exponential', 'fixed'], required: true },
      { key: 'delayMs', label: 'Delay (ms)', type: 'number' },
      { key: 'appliedTo', label: 'Applied To', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
    statuses: ['active', 'inactive'],
  },
};

export default featureConfig;
